### ISSUE TITLE
Support Flatpak installations

### ISSUE THREAD

**Issue by shayne** [tailscale-dev/vscode-tailscale#76]
To support Flatpak we'll need to run commands via `flatpak-spawn --host <command>`.

For detection, the env variables `container=flatpak` and `FLATPAK_ID=com.visualstudio.code` are set.

I tested `flatpak-spawn --host pkexec tailscale status`, and it provided the visual password prompt and the command worked as expected.

**Comment by marwan-at-work** [comment]
After some digging, there is a larger issue: `/var/run` in flatpak is not the same as the host even though `--filesystem=host`. Tailscaled runs in `/var/run/tailscale` which is why tsrelay LocalClient can't find the unix socket

**Comment by marwan-at-work** [comment]
Update: 

1. If we run `flatpak override --user --filesystem=/var/run/tailscale <vscode>`, flatpak ends up unable to run vscode in the first place due to this error: https://github.com/flatpak/flatpak/issues/3477#issuecomment-1387162221 (comment is the solution to undo it). 
2. Given the error above, since `/var/run` is a symlink to `/run`, then mounting `/run/tailscale` actually made things work (along with the above suggested changes to run flatpak-spawn).
